import { EditorView, basicSetup } from 'codemirror';
import { python } from '@codemirror/lang-python';

export function createFilesPanel(container, transport) {
  container.innerHTML = `
    <div class="files-manager">
      <div class="files-header">
        <span>File manager</span>
      </div>
      <pre id="filesStatus" class="files-status"></pre>

      <details class="files-section" open>
        <summary>
          On device
          <button id="filesRefresh" class="icon-button" title="Refresh device file list">Refresh</button>
        </summary>
        <ul id="filesList" class="files-list"></ul>
      </details>

      <details class="files-section" open>
        <summary>Blocks to code</summary>
        <div class="files-section-body">
          <div id="loadGeneratedCodeBtn" class="files-quick-item" title="Code generated by the current blocks">
            workspace.py <span class="files-quick-badge">automatic</span>
          </div>
        </div>
      </details>
    </div>

    <div class="files-editor">
      <div class="files-editor-toolbar">
        <button id="fileNewBtn" class="icon-button" title="Clear the editor and start a new file">New</button>
        <button id="fileOpenBtn" class="icon-button" title="Open a file from your computer">Open File</button>
        <input id="fileOpenInput" type="file" hidden />
        <button id="fileSaveAsBtn" class="icon-button" title="Save the editor's contents to your computer">Save As</button>
        <button id="fileCheckBtn" class="icon-button" title="Compile-check this code on the device without running it">Check Syntax</button>
        <input id="fileNameInput" type="text" placeholder="filename.py" />
      </div>
      <div id="fileEditor" class="files-code-editor"></div>
      <button id="fileSaveBtn">Save to device</button>
    </div>
  `;

  const listEl = container.querySelector('#filesList');
  const statusEl = container.querySelector('#filesStatus');
  const nameInput = container.querySelector('#fileNameInput');
  const editorEl = container.querySelector('#fileEditor');
  const openInput = container.querySelector('#fileOpenInput');

  const editor = new EditorView({
    doc: '',
    extensions: [basicSetup, python()],
    parent: editorEl,
  });

  function getContent() {
    return editor.state.doc.toString();
  }

  function setContent(text) {
    editor.dispatch({
      changes: { from: 0, to: editor.state.doc.length, insert: text },
    });
  }

  function setStatus(text) {
    statusEl.textContent = text;
  }

  function requireConnected() {
    if (!transport.isConnected) {
      setStatus('Connect to a device first.');
      return false;
    }
    return true;
  }

  /** Trigger a browser download of device file content, saved under its own filename. */
  function downloadToComputer(filename, content) {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function refresh() {
    if (!requireConnected()) return;
    setStatus('Listing files...');
    try {
      const files = await transport.listFiles();
      listEl.innerHTML = '';
      files.forEach((filename) => {
        const li = document.createElement('li');

        const nameSpan = document.createElement('span');
        nameSpan.textContent = filename;
        li.appendChild(nameSpan);

        const openBtn = document.createElement('button');
        openBtn.textContent = 'Open';
        openBtn.onclick = async () => {
          setStatus(`Reading ${filename}...`);
          try {
            const content = await transport.readFile(filename);
            nameInput.value = filename;
            setContent(content);
            setStatus(`Loaded ${filename}.`);
          } catch (err) {
            setStatus(`[error] ${err.message}`);
          }
        };
        li.appendChild(openBtn);

        const runBtn = document.createElement('button');
        runBtn.textContent = 'Run';
        runBtn.onclick = async () => {
          setStatus(`Running ${filename}...`);
          try {
            const { stdout, stderr } = await transport.runFile(filename);
            setStatus(`--- running ${filename} ---\n${stdout}${stderr ? `\n[error]\n${stderr}` : ''}`);
          } catch (err) {
            setStatus(`[error] ${err.message}`);
          }
        };
        li.appendChild(runBtn);

        const downloadBtn = document.createElement('button');
        downloadBtn.textContent = 'Download';
        downloadBtn.onclick = async () => {
          setStatus(`Downloading ${filename}...`);
          try {
            const content = await transport.readFile(filename);
            downloadToComputer(filename, content);
            setStatus(`Downloaded ${filename}.`);
          } catch (err) {
            setStatus(`[error] ${err.message}`);
          }
        };
        li.appendChild(downloadBtn);

        const deleteBtn = document.createElement('button');
        deleteBtn.textContent = 'Delete';
        deleteBtn.onclick = async () => {
          if (!confirm(`Delete ${filename} from the device?`)) {
            setStatus(`Delete cancelled for ${filename}.`);
            return;
          }
          setStatus(`Deleting ${filename}...`);
          try {
            await transport.deleteFile(filename);
            setStatus(`Deleted ${filename}.`);
            refresh();
          } catch (err) {
            setStatus(`[error] ${err.message}`);
          }
        };
        li.appendChild(deleteBtn);

        listEl.appendChild(li);
      });
      setStatus(`${files.length} file(s).`);
    } catch (err) {
      setStatus(`[error] ${err.message}`);
    }
  }

  container.querySelector('#filesRefresh').addEventListener('click', refresh);
  container.querySelector('#fileSaveBtn').addEventListener('click', async () => {
    const filename = nameInput.value.trim();
    if (!filename) {
      setStatus('Enter a filename first.');
      return;
    }
    if (!requireConnected()) return;
    setStatus(`Writing ${filename}...`);
    try {
      await transport.writeFile(filename, getContent());
      setStatus(`Saved ${filename}.`);
      refresh();
    } catch (err) {
      setStatus(`[error] ${err.message}`);
    }
  });

  // --- New / Open / Save As: plain local-editor actions, independent of ---
  // --- any device connection - same idea as a desktop IDE's File menu.  ---

  container.querySelector('#fileNewBtn').addEventListener('click', () => {
    nameInput.value = '';
    setContent('');
    setStatus('New file.');
  });

  container.querySelector('#fileOpenBtn').addEventListener('click', () => {
    openInput.click();
  });
  openInput.addEventListener('change', async () => {
    const file = openInput.files[0];
    if (!file) return;
    const content = await file.text();
    nameInput.value = file.name;
    setContent(content);
    setStatus(`Opened ${file.name} from your computer.`);
    openInput.value = '';
  });

  container.querySelector('#fileSaveAsBtn').addEventListener('click', () => {
    const filename = nameInput.value.trim() || 'untitled.py';
    downloadToComputer(filename, getContent());
    setStatus(`Saved ${filename} to your computer.`);
  });

  container.querySelector('#fileCheckBtn').addEventListener('click', async () => {
    if (!requireConnected()) return;
    const filename = nameInput.value.trim() || 'untitled.py';
    const code = getContent();
    if (!code.trim()) {
      setStatus('Nothing to check - the editor is empty.');
      return;
    }
    setStatus('Checking syntax...');
    try {
      const result = await transport.checkSyntax(code, filename);
      setStatus(result.ok
        ? `${filename} compiles with no syntax errors.`
        : `[syntax error] ${result.message}`);
    } catch (err) {
      setStatus(`[error] ${err.message}`);
    }
  });

  return {
    refresh,
    setStatus,
    // Load the current workspace's generated code into the editor, so it can
    // be reviewed, hand-edited, and saved to the device like any other file.
    loadCode(code, filename) {
      nameInput.value = filename;
      setContent(code);
      setStatus(`Loaded ${filename} from the current blocks.`);
    },
    // Write a driver file straight to the device - used by the toolbox's
    // per-sensor "Install X driver" flyout buttons.
    async installDriver(filename, source) {
      if (!transport.isConnected) {
        setStatus('Connect to a device first.');
        return;
      }
      setStatus(`Installing ${filename}...`);
      try {
        await transport.writeFile(filename, source);
        setStatus(`Installed ${filename}.`);
        refresh();
      } catch (err) {
        setStatus(`[error] ${err.message}`);
      }
    },
  };
}
