import * as Blockly from 'blockly/core';

Blockly.common.defineBlocksWithJsonArray([
  {
    type: 'sensor_dht_start',
    message0: 'start DHT sensor type %1 on pin %2',
    args0: [
      {
        type: 'field_dropdown',
        name: 'TYPE',
        options: [
          ['DHT11', 'DHT11'],
          ['DHT22', 'DHT22'],
        ],
      },
      { type: 'input_value', name: 'PIN', check: 'Number' },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 305,
    tooltip: 'Set up a DHT11/DHT22 temperature+humidity sensor.',
  },
  {
    type: 'sensor_dht_measure',
    message0: 'update DHT sensor reading',
    previousStatement: null,
    nextStatement: null,
    colour: 305,
    tooltip: 'Take a new reading from the DHT sensor.',
  },
  {
    type: 'sensor_dht_temperature',
    message0: 'DHT temperature (°C)',
    output: 'Number',
    colour: 305,
    tooltip: 'Temperature from the last DHT reading, in Celsius.',
  },
  {
    type: 'sensor_dht_humidity',
    message0: 'DHT humidity (%)',
    output: 'Number',
    colour: 305,
    tooltip: 'Relative humidity from the last DHT reading.',
  },
  // --- Ultrasound (HC-SR04) ------------------------------------------
  {
    type: 'sensor_hcsr04_init',
    message0: 'start HC-SR04 ultrasound sensor trigger pin %1 echo pin %2',
    args0: [
      { type: 'input_value', name: 'TRIGGER', check: 'Number' },
      { type: 'input_value', name: 'ECHO', check: 'Number' },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 305,
    tooltip: 'Set up an HC-SR04 ultrasonic distance sensor.',
  },
  {
    type: 'sensor_hcsr04_distance',
    message0: 'HC-SR04 distance (cm)',
    output: 'Number',
    colour: 305,
    tooltip: 'Measure distance in centimetres.',
  },
  // --- OneWire (DS18B20) ----------------------------------------------
  {
    type: 'sensor_ds18b20_init',
    message0: 'start DS18B20 sensor(s) on pin %1',
    args0: [{ type: 'input_value', name: 'PIN', check: 'Number' }],
    previousStatement: null,
    nextStatement: null,
    colour: 305,
    tooltip: 'Set up a OneWire bus for DS18B20 temperature sensors.',
  },
  {
    type: 'sensor_ds18b20_scan',
    message0: 'DS18B20 list of sensor addresses',
    output: null,
    colour: 305,
    tooltip: 'Scan the OneWire bus and return a list of sensor ROM addresses.',
  },
  {
    type: 'sensor_ds18b20_convert',
    message0: 'DS18B20 start temperature conversion',
    previousStatement: null,
    nextStatement: null,
    colour: 305,
    tooltip: 'Ask all sensors on the bus to take a new reading.',
  },
  {
    type: 'sensor_ds18b20_read_temp',
    message0: 'DS18B20 read temperature of %1',
    args0: [{ type: 'input_value', name: 'ROM' }],
    output: 'Number',
    colour: 305,
    tooltip: "Read one sensor's temperature (pass an address from the scan block).",
  },
  // --- Inertial Measurement (MPU6050) ---------------------------------
  {
    type: 'sensor_mpu6050_init',
    message0: 'start MPU6050 IMU SCL pin %1 SDA pin %2',
    args0: [
      { type: 'input_value', name: 'SCL', check: 'Number' },
      { type: 'input_value', name: 'SDA', check: 'Number' },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 305,
    tooltip: 'Set up an MPU6050 accelerometer + gyroscope over I2C.',
  },
  {
    type: 'sensor_mpu6050_accel',
    message0: 'MPU6050 acceleration %1 (g)',
    args0: [
      {
        type: 'field_dropdown',
        name: 'AXIS',
        options: [
          ['X', 'X'],
          ['Y', 'Y'],
          ['Z', 'Z'],
        ],
      },
    ],
    output: 'Number',
    colour: 305,
    tooltip: 'Acceleration on one axis, in g.',
  },
  {
    type: 'sensor_mpu6050_gyro',
    message0: 'MPU6050 rotation %1 (deg/s)',
    args0: [
      {
        type: 'field_dropdown',
        name: 'AXIS',
        options: [
          ['X', 'X'],
          ['Y', 'Y'],
          ['Z', 'Z'],
        ],
      },
    ],
    output: 'Number',
    colour: 305,
    tooltip: 'Rotation rate on one axis, in degrees per second.',
  },
  // --- RFID Reader (RC522) ---------------------------------------------
  {
    type: 'sensor_rfid_init',
    message0: 'start RC522 RFID reader SCK %1 MOSI %2 MISO %3 RST %4 CS %5',
    args0: [
      { type: 'input_value', name: 'SCK', check: 'Number' },
      { type: 'input_value', name: 'MOSI', check: 'Number' },
      { type: 'input_value', name: 'MISO', check: 'Number' },
      { type: 'input_value', name: 'RST', check: 'Number' },
      { type: 'input_value', name: 'CS', check: 'Number' },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 305,
    tooltip: 'Set up an RC522 RFID reader over SPI.',
  },
  {
    type: 'sensor_rfid_card_present',
    message0: 'RFID card present?',
    output: 'Boolean',
    colour: 305,
    tooltip: 'True if a card is currently in range.',
  },
  {
    type: 'sensor_rfid_read_uid',
    message0: 'RFID read card UID',
    output: 'String',
    colour: 305,
    tooltip: "Read the present card's UID as a hex string, or an empty string if none.",
  },
  // --- Rotary Encoder --------------------------------------------------
  {
    type: 'sensor_encoder_init',
    message0: 'start rotary encoder pin A %1 pin B %2',
    args0: [
      { type: 'input_value', name: 'PIN_A', check: 'Number' },
      { type: 'input_value', name: 'PIN_B', check: 'Number' },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 305,
    tooltip: 'Set up a quadrature rotary encoder.',
  },
  {
    type: 'sensor_encoder_position',
    message0: 'encoder position',
    output: 'Number',
    colour: 305,
    tooltip: 'Current encoder position (increments/decrements per detent).',
  },
  {
    type: 'sensor_encoder_reset',
    message0: 'reset encoder position',
    previousStatement: null,
    nextStatement: null,
    colour: 305,
    tooltip: 'Reset the encoder position back to zero.',
  },
  // --- Anemometer (wind speed pulse counter) --------------------------
  {
    type: 'sensor_anemometer_init',
    message0: 'start anemometer on pin %1',
    args0: [{ type: 'input_value', name: 'PIN', check: 'Number' }],
    previousStatement: null,
    nextStatement: null,
    colour: 305,
    tooltip: 'Count pulses from an anemometer (wind speed sensor) via interrupt.',
  },
  {
    type: 'sensor_anemometer_count',
    message0: 'anemometer pulse count',
    output: 'Number',
    colour: 305,
    tooltip: 'Pulses counted since init or the last reset.',
  },
  {
    type: 'sensor_anemometer_reset',
    message0: 'reset anemometer count',
    previousStatement: null,
    nextStatement: null,
    colour: 305,
    tooltip: 'Reset the anemometer pulse count back to zero.',
  },
  // --- Rain gauge (pulse counter) --------------------------------------
  {
    type: 'sensor_raingauge_init',
    message0: 'start rain gauge on pin %1',
    args0: [{ type: 'input_value', name: 'PIN', check: 'Number' }],
    previousStatement: null,
    nextStatement: null,
    colour: 305,
    tooltip: 'Count tips from a tipping-bucket rain gauge via interrupt.',
  },
  {
    type: 'sensor_raingauge_count',
    message0: 'rain gauge tip count',
    output: 'Number',
    colour: 305,
    tooltip: 'Tips counted since init or the last reset.',
  },
  {
    type: 'sensor_raingauge_reset',
    message0: 'reset rain gauge count',
    previousStatement: null,
    nextStatement: null,
    colour: 305,
    tooltip: 'Reset the rain gauge tip count back to zero.',
  },
]);
